version: '3.8'

services:
  resurface:
    image: resurfaceio/resurface:3.2.6
    container_name: openresty_resurface
    ports:
      - '7700:7700'
      - '7701:7701'

  openresty:
    image: test-openresty
    container_name: openresty_with_logger
    ports:
      - '8000:80'
    volumes:
      - ./server.conf:/etc/nginx/conf.d/default.conf